# Generated by Django 6.0.3 on 2026-03-26 20:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_draft_draftpick'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='draft',
            name='duration_seconds',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='VsBattle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('completed', 'Completed'), ('declined', 'Declined'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('challenged', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battles_received', to=settings.AUTH_USER_MODEL)),
                ('challenged_draft', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='battle_as_challenged', to='game.draft')),
                ('challenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battles_sent', to=settings.AUTH_USER_MODEL)),
                ('challenger_draft', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='battle_as_challenger', to='game.draft')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendships_sent', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendships_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('from_user', 'to_user')},
            },
        ),
        migrations.CreateModel(
            name='VsBattleRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.IntegerField()),
                ('tier1', models.CharField(max_length=10)),
                ('tier2', models.CharField(max_length=10)),
                ('tier3', models.CharField(max_length=10)),
                ('battle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='game.vsbattle')),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='game.player')),
                ('player2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='game.player')),
                ('player3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='game.player')),
            ],
            options={
                'ordering': ['round_number'],
                'unique_together': {('battle', 'round_number')},
            },
        ),
    ]
