# Generated by Django 6.0.3 on 2026-03-28 05:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_draft_duration_seconds_vsbattle_friendship_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SoloDraftProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_round', models.IntegerField(default=1)),
                ('drafted_slots', models.JSONField(default=dict)),
                ('drafted_player_ids', models.JSONField(default=list)),
                ('current_pool', models.JSONField(default=list)),
                ('picked_this_round', models.BooleanField(default=False)),
                ('start_time', models.BigIntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='solo_draft_progress', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
