# Generated by Django 6.0.3 on 2026-03-28 05:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_solodraftprogress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VsDraftProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_round', models.IntegerField(default=1)),
                ('drafted_slots', models.JSONField(default=dict)),
                ('drafted_player_ids', models.JSONField(default=list)),
                ('current_pool', models.JSONField(default=list)),
                ('picked_this_round', models.BooleanField(default=False)),
                ('start_time', models.BigIntegerField(blank=True, null=True)),
                ('battle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draft_progress', to='game.vsbattle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vs_draft_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('battle', 'user')},
            },
        ),
    ]
