# Generated by Django 6.0.3 on 2026-03-28 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_vsbattle_is_public_alter_vsbattle_challenged'),
    ]

    operations = [
        migrations.AddField(
            model_name='vsbattle',
            name='link_code',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
    ]
